export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_LOADING: 'SET_LOADING',
  SET_LOADING_SIGNUP: 'SET_LOADING_SIGNUP',
  SET_ERROR: 'SET_ERROR',
  SET_ERROR_SIGNUP: 'SET_ERROR_SIGNUP',
  LOGOUT: 'LOGOUT',
};